apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-ingress
  namespace: web
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  # IMPORTANT: For local testing, add this to your hosts file:
  # 20.81.106.177 testdomain.local
  rules:
    - host: testdomain.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: django-svc
                port:
                  number: 80
