name: CI/CD AKS Pipeline

on:
  push:
    branches: [main]

env:
  RG_NAME: rg-django-app-aks
  AKS_NAME: aks-django-app
  ACR_NAME: acrdjangoapp
  IMAGE_NAME: django-app
  NAMESPACE: web

permissions:
  contents: write
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_FEDERATED_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          IMAGE="$ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG"
          docker build -f Dockerfile.prod -t $IMAGE .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: ACR login
        run: az acr login --name $ACR_NAME

      - name: Push Docker image
        run: docker push $IMAGE

  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set IMAGE variable
        run: echo "IMAGE=$ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}" >> $GITHUB_ENV

      - name: Update manifest image tag
        run: |
          sed -i "s|image: .*$|image: $IMAGE|" k8s/deployment.yaml

      - name: Commit manifest
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to $IMAGE"
          git push

  deploy:
    needs: update-manifest
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_FEDERATED_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group $RG_NAME --name $AKS_NAME --overwrite-existing

      - name: Prepare namespace and secrets
        run: |
          kubectl apply -f k8s/namespace.yaml
          if [ -f k8s/secret.yaml ]; then kubectl apply -f k8s/secret.yaml; fi

      - name: Deploy app
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml
          kubectl rollout status deployment/django-app -n $NAMESPACE

      - name: Show ingress address
        run: |
          kubectl get svc -n ingress-nginx
          kubectl get ingress -n $NAMESPACE
